[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vivida-utils"
version = "0.1.0"
description = "Vivida App utilities and web scraping services"
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4",
    "selenium",
    "undetected-chromedriver"
]

[tool.setuptools.packages.find]
where = ["."]